// Code generated by tools/gen from spec/openapi.yaml. DO NOT EDIT.

package bizgo_test

import (
	"context"
	"strings"
	"time"

	bizgo "github.com/icomm-api/bizgo-sdk-comm-go"
)

// generatedCalls calls every generated method once with valid placeholder arguments
// (path values are "PATH-<name>"). The key is the operationId ("+files" for the multipart variant).
// It returns the method's result (nil for methods without one, see generatedVoid).
var generatedCalls = map[string]func(context.Context, *bizgo.Client) (any, error){
	"uploadBrandMessageDefaultImage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Files.UploadBrandMessageDefault(ctx, &bizgo.BrandMessageDefaultFileUploadRequest{File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"uploadBrandMessageWideImage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Files.UploadBrandMessageWide(ctx, &bizgo.BrandMessageWideFileUploadRequest{File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"uploadBrandMessageWideItemListFirstImage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Files.UploadBrandMessageWideItemListFirst(ctx, &bizgo.BrandMessageWideItemListFirstFileUploadRequest{File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"uploadBrandMessageWideItemListImage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Files.UploadBrandMessageWideItemList(ctx, &bizgo.BrandMessageWideItemListFileUploadRequest{File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"uploadBrandMessageCarouselFeedImage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Files.UploadBrandMessageCarouselFeed(ctx, &bizgo.BrandMessageCarouselFeedFileUploadRequest{File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"uploadBrandMessageCarouselCommerceImage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Files.UploadBrandMessageCarouselCommerce(ctx, &bizgo.BrandMessageCarouselCommerceFileUploadRequest{File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"createReservation": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Reservations.Create(ctx, &bizgo.ReservationCreateRequest{Destinations: []bizgo.Destination{{To: "01000000000"}}, MessageFlow: []bizgo.ReservationMessageFlowItem{{SMS: &bizgo.SMSMessage{From: "01000000000", Text: "x"}}}, ResvSendTime: "x"})
	},
	"listReservations": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Reservations.List(ctx, bizgo.ListReservationsParams{ResvSendTime: bizgo.Date(2026, time.January, 2)})
	},
	"getReservation": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Reservations.Get(ctx, "PATH-resvKey")
	},
	"updateReservation": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Reservations.Update(ctx, "PATH-resvKey", &bizgo.ReservationUpdateRequest{ResvSendTime: "x"})
	},
	"cancelReservation": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Reservations.Cancel(ctx, "PATH-resvKey")
	},
	"stopReservation": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Reservations.Pause(ctx, "PATH-resvKey")
	},
	"resumeReservation": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Reservations.Resume(ctx, "PATH-resvKey")
	},
	"listReservationRecipients": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Reservations.Recipients.List(ctx, "PATH-resvKey", bizgo.ListReservationRecipientsParams{})
	},
	"addReservationRecipients": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Reservations.Recipients.Create(ctx, "PATH-resvKey", &bizgo.ReservationRecipientCreateRequest{Destinations: []bizgo.Destination{{To: "01000000000"}}})
	},
	"deleteReservationRecipient": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Reservations.Recipients.Delete(ctx, "PATH-resvKey", "PATH-msgKey")
	},
	"getAlimtalkInsight": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Insights.Alimtalk.Get(ctx, bizgo.GetAlimtalkInsightParams{StartDate: bizgo.Date(2026, time.January, 2), EndDate: bizgo.Date(2026, time.January, 2), SenderKey: []string{"Q-senderKey"}})
	},
	"getAlimtalkHourlyInsight": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Insights.Alimtalk.GetHourly(ctx, bizgo.GetAlimtalkHourlyInsightParams{StartDate: bizgo.Date(2026, time.January, 2), EndDate: bizgo.Date(2026, time.January, 2), SenderKey: []string{"Q-senderKey"}})
	},
	"getAlimtalkTemplateInsight": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Insights.Alimtalk.GetByTemplate(ctx, bizgo.GetAlimtalkTemplateInsightParams{StartDate: bizgo.Date(2026, time.January, 2), EndDate: bizgo.Date(2026, time.January, 2), SenderKey: []string{"Q-senderKey"}})
	},
	"getBrandMessageInsight": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Insights.BrandMessage.Get(ctx, bizgo.GetBrandMessageInsightParams{StartDate: bizgo.Date(2026, time.January, 2), EndDate: bizgo.Date(2026, time.January, 2), SenderKey: []string{"Q-senderKey"}})
	},
	"getBrandMessageHourlyInsight": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Insights.BrandMessage.GetHourly(ctx, bizgo.GetBrandMessageHourlyInsightParams{StartDate: bizgo.Date(2026, time.January, 2), EndDate: bizgo.Date(2026, time.January, 2), SenderKey: []string{"Q-senderKey"}})
	},
	"getBrandMessageTemplateInsight": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Insights.BrandMessage.GetByTemplate(ctx, bizgo.GetBrandMessageTemplateInsightParams{StartDate: bizgo.Date(2026, time.January, 2), EndDate: bizgo.Date(2026, time.January, 2), SenderKey: []string{"Q-senderKey"}})
	},
	"getRcsMessageInsight": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Insights.RCS.GetMessage(ctx, "PATH-brandId", bizgo.GetRCSMessageInsightParams{StartDate: bizgo.Date(2026, time.January, 2), EndDate: bizgo.Date(2026, time.January, 2), GroupID: "Q-groupId"})
	},
	"getRcsMessageButtonInsight": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Insights.RCS.GetMessageButton(ctx, "PATH-brandId", bizgo.GetRCSMessageButtonInsightParams{StartDate: bizgo.Date(2026, time.January, 2), EndDate: bizgo.Date(2026, time.January, 2), GroupID: "Q-groupId"})
	},
	"getRcsPersistentMenuInsight": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Insights.RCS.GetPersistentMenu(ctx, "PATH-brandId", bizgo.GetRCSPersistentMenuInsightParams{StartDate: bizgo.Date(2026, time.January, 2), EndDate: bizgo.Date(2026, time.January, 2), ChatbotID: "Q-chatbotId"})
	},
	"getRcsBrandProfileInsight": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Insights.RCS.GetBrandProfile(ctx, "PATH-brandId", bizgo.GetRCSBrandProfileInsightParams{StartDate: bizgo.Date(2026, time.January, 2), EndDate: bizgo.Date(2026, time.January, 2)})
	},
	"requestKakaoSenderToken": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Kakao.Senders.RequestToken(ctx, &bizgo.KakaoSenderTokenRequest{YellowID: "x", PhoneNumber: "01000000000"})
	},
	"findKakaoSender": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Kakao.Senders.Find(ctx, bizgo.FindKakaoSenderParams{})
	},
	"createKakaoSender": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Kakao.Senders.Create(ctx, &bizgo.KakaoSenderCreateRequest{YellowID: "x", CategoryCode: "01000000000"}, bizgo.CreateKakaoSenderParams{Token: "Q-token", PhoneNumber: "Q-phoneNumber"})
	},
	"listKakaoSenderProfiles": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Kakao.Senders.List(ctx, bizgo.ListKakaoSenderProfilesParams{})
	},
	"getKakaoSender": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Kakao.Senders.Get(ctx, bizgo.GetKakaoSenderParams{SenderKey: "Q-senderKey"})
	},
	"recoverKakaoSender": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Kakao.Senders.Recover(ctx, &bizgo.KakaoSenderRecoverRequest{SenderKey: "x"})
	},
	"listKakaoSenderCategories": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Kakao.Categories.List(ctx)
	},
	"getKakaoSenderCategory": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Kakao.Categories.Get(ctx, bizgo.GetKakaoSenderCategoryParams{Code: "Q-code"})
	},
	"listKakaoGroups": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Kakao.Groups.List(ctx, bizgo.ListKakaoGroupsParams{})
	},
	"addKakaoGroupSender": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Kakao.Groups.AddSender(ctx, &bizgo.KakaoGroupSenderAddRequest{GroupKey: "x", SenderKey: "x"})
	},
	"removeKakaoGroupSender": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Kakao.Groups.RemoveSender(ctx, "PATH-groupKey", "PATH-senderKey")
	},
	"getKakaoSenderSanction": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Kakao.Sanctions.GetSender(ctx, bizgo.GetKakaoSenderSanctionParams{Date: "20260101", SenderKey: "Q-senderKey"})
	},
	"getKakaoGroupTemplateSenderExclusion": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Kakao.Sanctions.GetGroupTemplateExclusion(ctx, bizgo.GetKakaoGroupTemplateSenderExclusionParams{Date: "20260101", SenderKey: "Q-senderKey", GroupKey: "Q-groupKey", TemplateCode: "Q-templateCode"})
	},
	"getKakaoTemplateSanction": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Kakao.Sanctions.GetTemplate(ctx, bizgo.GetKakaoTemplateSanctionParams{Date: "20260101", SenderKey: "Q-senderKey", TemplateCode: "Q-templateCode"})
	},
	"getAlimtalkTemplate": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Alimtalk.Templates.Get(ctx, bizgo.GetAlimtalkTemplateParams{SenderKey: "Q-senderKey", TemplateCode: "Q-templateCode"})
	},
	"updateAlimtalkTemplate": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Alimtalk.Templates.Update(ctx, &bizgo.AlimtalkTemplateSaveRequest{Alimtalk: &bizgo.AlimtalkTemplateBody{SenderKey: "x", TemplateName: "x", TemplateCode: "x", TemplateMessageType: "x", TemplateEmphasizeType: "x", Text: "x"}})
	},
	"createAlimtalkTemplate": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Alimtalk.Templates.Create(ctx, &bizgo.AlimtalkTemplateSaveRequest{Alimtalk: &bizgo.AlimtalkTemplateBody{SenderKey: "x", TemplateName: "x", TemplateCode: "x", TemplateMessageType: "x", TemplateEmphasizeType: "x", Text: "x"}})
	},
	"listAlimtalkTemplates": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Alimtalk.Templates.List(ctx, bizgo.ListAlimtalkTemplatesParams{SenderKey: "Q-senderKey"})
	},
	"listModifiedAlimtalkTemplates": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Alimtalk.Templates.ListModified(ctx, bizgo.ListModifiedAlimtalkTemplatesParams{SenderKey: "Q-senderKey"})
	},
	"deleteAlimtalkTemplate": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Alimtalk.Templates.Delete(ctx, "PATH-senderKey", "PATH-templateCode")
	},
	"uploadAlimtalkTemplateImage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Files.UploadAlimtalkTemplateImage(ctx, &bizgo.AlimtalkTemplateImageUploadRequest{File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"uploadAlimtalkItemHighlightImage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Files.UploadAlimtalkItemHighlightImage(ctx, &bizgo.AlimtalkTemplateItemHighlightImageUploadRequest{File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"listAlimtalkTemplateCategories": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Alimtalk.TemplateCategories.List(ctx, bizgo.ListAlimtalkTemplateCategoriesParams{})
	},
	"requestAlimtalkTemplateInspection": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Alimtalk.Templates.RequestInspection(ctx, &bizgo.AlimtalkTemplateInspectionRequest{Alimtalk: &bizgo.AlimtalkTemplateInspectionRequestAlimtalk{SenderKey: "x", TemplateCode: "x"}})
	},
	"requestAlimtalkTemplateInspection+files": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Alimtalk.Templates.RequestInspectionWithFiles(ctx, &bizgo.AlimtalkTemplateInspectionFileRequest{SenderKey: "x", TemplateCode: "x", Comment: "x"})
	},
	"cancelAlimtalkTemplateInspection": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Alimtalk.Templates.CancelInspection(ctx, &bizgo.AlimtalkTemplateInspectionCancelRequest{Alimtalk: &bizgo.AlimtalkTemplateInspectionCancelRequestAlimtalk{SenderKey: "x", TemplateCode: "x"}})
	},
	"listAlimtalkPublicTemplates": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Alimtalk.PublicTemplates.List(ctx, bizgo.ListAlimtalkPublicTemplatesParams{})
	},
	"getBrandMessageGroupSend": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.GroupSends.Get(ctx, bizgo.GetBrandMessageGroupSendParams{SenderKey: "Q-senderKey", RequestID: 1})
	},
	"createBrandMessageGroupSend": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.GroupSends.Create(ctx, &bizgo.BrandMessageGroupSendCreateRequest{Brandmessage: &bizgo.BrandMessageGroupSendCreateRequestBrandmessage{SenderKey: "x", TemplateCode: "x", SendStartAt: "x"}})
	},
	"resumeBrandMessageGroupSend": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.GroupSends.Resume(ctx, &bizgo.BrandMessageGroupSendControlRequest{Brandmessage: &bizgo.BrandMessageGroupSendControlRequestBrandmessage{SenderKey: "x", RequestID: "x"}})
	},
	"pauseBrandMessageGroupSend": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.GroupSends.Pause(ctx, &bizgo.BrandMessageGroupSendControlRequest{Brandmessage: &bizgo.BrandMessageGroupSendControlRequestBrandmessage{SenderKey: "x", RequestID: "x"}})
	},
	"terminateBrandMessageGroupSend": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.GroupSends.Terminate(ctx, &bizgo.BrandMessageGroupSendControlRequest{Brandmessage: &bizgo.BrandMessageGroupSendControlRequestBrandmessage{SenderKey: "x", RequestID: "x"}})
	},
	"checkBrandMessageAudiencePossible": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.Audience.CheckPossible(ctx, bizgo.CheckBrandMessageAudiencePossibleParams{SenderKey: "Q-senderKey", MsgType: "Q-msgType"})
	},
	"checkBrandMessageAudiencePossibleByPhoneNumbers": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.Audience.CheckPossibleByPhoneNumbers(ctx, &bizgo.BrandMessageAudiencePossibleByPhoneNumbersRequest{SenderKey: "x", PhoneNumbers: []string{"01000000000", "01000000000", "01000000000", "01000000000", "01000000000", "01000000000", "01000000000", "01000000000", "01000000000", "01000000000"}})
	},
	"getBrandMessageFriendCount": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.Audience.GetFriendCount(ctx, bizgo.GetBrandMessageFriendCountParams{SenderKey: "Q-senderKey"})
	},
	"estimateBrandMessageGroupSendDuration": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.Audience.Estimate(ctx, bizgo.EstimateBrandMessageGroupSendDurationParams{SenderKey: "Q-senderKey", StartTime: bizgo.Date(2026, time.January, 2), Count: 1})
	},
	"checkBrandMessageSendPermission": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.BrandMessage.Permissions.Check(ctx, bizgo.CheckBrandMessageSendPermissionParams{SenderKey: "Q-senderKey"})
	},
	"applyBrandMessageSendPermission": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.BrandMessage.Permissions.Apply(ctx, &bizgo.BrandMessagePermissionApplyRequest{BrandMessage: &bizgo.BrandMessagePermissionApplyRequestBrandMessage{SenderKey: "x"}})
	},
	"uploadBrandMessageCatalogImage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Files.UploadBrandMessageCatalog(ctx, &bizgo.BrandMessageCatalogFileUploadRequest{File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"uploadBrandMessageCatalogOddFirstImage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Files.UploadBrandMessageCatalogOddFirst(ctx, &bizgo.BrandMessageCatalogOddFirstFileUploadRequest{File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"registerBrandMessageVideoUpload": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.Videos.RegisterUpload(ctx, &bizgo.BrandMessageVideoUploadRegisterRequest{SenderKey: "x", FileName: "x", FileSize: 1})
	},
	"registerBrandMessageExistingVideo": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.Videos.RegisterExisting(ctx, &bizgo.BrandMessageVideoRegisterRequest{SenderKey: "x"})
	},
	"getBrandMessageVideo": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.Videos.Get(ctx, bizgo.GetBrandMessageVideoParams{Vid: "Q-vid", SenderKey: "Q-senderKey"})
	},
	"listBrandMessageVideos": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.Videos.List(ctx, bizgo.ListBrandMessageVideosParams{SenderKey: "Q-senderKey"})
	},
	"getBrandMessageTemplate": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.Templates.Get(ctx, bizgo.GetBrandMessageTemplateParams{SenderKey: "Q-senderKey", TemplateCode: "Q-templateCode"})
	},
	"updateBrandMessageTemplate": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.Templates.Update(ctx, &bizgo.BrandMessageTemplateRequest{Brandmessage: &bizgo.BrandMessageTemplateInput{SenderKey: "x", SenderKeyType: "x", SendType: "basic", TemplateName: "x", MsgType: "x"}})
	},
	"createBrandMessageTemplate": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.Templates.Create(ctx, &bizgo.BrandMessageTemplateRequest{Brandmessage: &bizgo.BrandMessageTemplateInput{SenderKey: "x", SenderKeyType: "x", SendType: "basic", TemplateName: "x", MsgType: "x"}})
	},
	"listBrandMessageTemplates": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.Templates.List(ctx, bizgo.ListBrandMessageTemplatesParams{SenderKey: "Q-senderKey"})
	},
	"listBrandMessageTemplatesLastModified": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.Templates.ListLastModified(ctx, bizgo.ListBrandMessageTemplatesLastModifiedParams{SenderKey: "Q-senderKey"})
	},
	"deleteBrandMessageTemplate": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.BrandMessage.Templates.Delete(ctx, "PATH-senderKey", "PATH-templateCode")
	},
	"listBrandMessageGroupTags": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.GroupTags.List(ctx, bizgo.ListBrandMessageGroupTagsParams{SenderKey: "Q-senderKey"})
	},
	"getBrandMessageGroupTag": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.GroupTags.Get(ctx, bizgo.GetBrandMessageGroupTagParams{SenderKey: "Q-senderKey", GroupTagKey: "Q-groupTagKey"})
	},
	"updateBrandMessageGroupTag": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.GroupTags.Update(ctx, &bizgo.BrandMessageGroupTagRequest{GroupTag: &bizgo.BrandMessageGroupTagRequestGroupTag{GroupTagKey: "x", GroupTagName: "x"}})
	},
	"createBrandMessageGroupTag": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.GroupTags.Create(ctx, &bizgo.BrandMessageGroupTagRequest{GroupTag: &bizgo.BrandMessageGroupTagRequestGroupTag{GroupTagKey: "x", GroupTagName: "x"}})
	},
	"deleteBrandMessageGroupTag": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.BrandMessage.GroupTags.Delete(ctx, "PATH-senderKey", "PATH-groupTagKey")
	},
	"uploadBrandMessageFriendGroupFile": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.FriendGroups.UploadFile(ctx, &bizgo.BrandMessageFriendGroupFileUploadRequest{SenderKey: "x", File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"getBrandMessageFriendGroup": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.FriendGroups.Get(ctx, bizgo.GetBrandMessageFriendGroupParams{SenderKey: "Q-senderKey", FriendGroupKey: "Q-friendGroupKey"})
	},
	"createBrandMessageFriendGroup": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.FriendGroups.Create(ctx, &bizgo.BrandMessageFriendGroupRequest{FriendGroup: &bizgo.BrandMessageFriendGroupRequestFriendGroup{SenderKey: "x", FriendGroupKey: "x"}})
	},
	"listBrandMessageFriendGroups": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.FriendGroups.List(ctx, bizgo.ListBrandMessageFriendGroupsParams{SenderKey: "Q-senderKey"})
	},
	"deleteBrandMessageFriendGroup": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.BrandMessage.FriendGroups.Delete(ctx, "PATH-senderKey", "PATH-friendGroupKey")
	},
	"addBrandMessageFriendGroupPhoneNumbers": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.FriendGroups.AddPhoneNumbers(ctx, &bizgo.BrandMessageFriendGroupRequest{FriendGroup: &bizgo.BrandMessageFriendGroupRequestFriendGroup{SenderKey: "x", FriendGroupKey: "x"}})
	},
	"deleteBrandMessageFriendGroupPhoneNumbers": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.FriendGroups.DeletePhoneNumbers(ctx, &bizgo.BrandMessageFriendGroupRequest{FriendGroup: &bizgo.BrandMessageFriendGroupRequestFriendGroup{SenderKey: "x", FriendGroupKey: "x"}})
	},
	"listBrandMessageFriendGroupPhoneNumberRequests": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.FriendGroups.ListPhoneNumberRequests(ctx, bizgo.ListBrandMessageFriendGroupPhoneNumberRequestsParams{SenderKey: "Q-senderKey", FriendGroupKey: "Q-friendGroupKey"})
	},
	"getBrandMessageFriendGroupPhoneNumberRequest": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.FriendGroups.GetPhoneNumberRequest(ctx, bizgo.GetBrandMessageFriendGroupPhoneNumberRequestParams{SenderKey: "Q-senderKey", FriendGroupKey: "Q-friendGroupKey", RequestID: "Q-requestId"})
	},
	"uploadBrandMessageMarketingAgreeEvidence": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.BrandMessage.MarketingAgreements.UploadEvidence(ctx, &bizgo.BrandMessageMarketingAgreeUploadRequest{SenderKey: "x", File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"registerBrandMessageUnsubscribeContent": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.BrandMessage.UnsubscribeContents.Register(ctx, &bizgo.BrandMessageUnsubscribeContentRequest{Brandmessage: &bizgo.BrandMessageUnsubscribeContentRequestBrandmessage{SenderKey: "x", UnsubscribePhoneNumber: "01000000000"}})
	},
	"getRcsBrand": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Brands.Get(ctx, bizgo.GetRCSBrandParams{BrandID: "Q-brandId"})
	},
	"updateRcsBrand": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Brands.Update(ctx, &bizgo.RCSBrandUpdateRequest{BrandID: "x", RegBrand: &bizgo.RCSBrandUpdateRequestRegBrand{BrandID: "x", Name: "x"}})
	},
	"listRcsChatbots": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Chatbots.List(ctx, bizgo.ListRCSChatbotsParams{BrandID: "Q-brandId"})
	},
	"getRcsChatbot": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Chatbots.Get(ctx, bizgo.GetRCSChatbotParams{BrandID: "Q-brandId", ChatbotID: "Q-chatbotId"})
	},
	"updateRcsChatbot": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Chatbots.Update(ctx, &bizgo.RCSChatbotUpdateRequest{BrandID: "x", Chatbot: &bizgo.RCSChatbot{}, SubNumCertificate: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"cancelRcsChatbotApproval": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Chatbots.Cancel(ctx, "PATH-brandId", "PATH-chatbotId")
	},
	"deleteRcsChatbot": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Chatbots.Delete(ctx, "PATH-brandId", "PATH-chatbotId")
	},
	"getRcsChatbotUsableQueries": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Chatbots.GetUsableQueries(ctx, "PATH-chatbotId")
	},
	"listRcsCommonFormats": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.CommonFormats.List(ctx)
	},
	"getRcsCommonFormat": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.CommonFormats.Get(ctx, bizgo.GetRCSCommonFormatParams{MessagebaseID: "Q-messagebaseId"})
	},
	"listRcsTemplateForms": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.TemplateForms.List(ctx, bizgo.ListRCSTemplateFormsParams{})
	},
	"getRcsTemplateForm": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.TemplateForms.Get(ctx, bizgo.GetRCSTemplateFormParams{MessagebaseformID: "Q-messagebaseformId"})
	},
	"listRcsTemplates": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Templates.List(ctx)
	},
	"getRcsTemplate": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Templates.Get(ctx, bizgo.GetRCSTemplateParams{MessagebaseID: "Q-messagebaseId"})
	},
	"updateRcsTemplate": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Templates.Update(ctx, &bizgo.RCSTemplateRequest{RCS: &bizgo.RCSTemplateDefinition{BrandID: "x", TemplateName: "x", Body: []bizgo.RCSTemplateBodyParam{{Param: "SAMPLE", IsMandatory: "x"}}, Buttons: []bizgo.RCSTemplateButton{{}}}})
	},
	"createRcsTemplate": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Templates.Create(ctx, &bizgo.RCSTemplateRequest{RCS: &bizgo.RCSTemplateDefinition{BrandID: "x", TemplateName: "x", Body: []bizgo.RCSTemplateBodyParam{{Param: "SAMPLE", IsMandatory: "x"}}, Buttons: []bizgo.RCSTemplateButton{{}}}})
	},
	"cancelRcsTemplateApproval": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Templates.Cancel(ctx, "PATH-brandId", "PATH-messagebaseId")
	},
	"deleteRcsTemplate": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.Templates.Delete(ctx, "PATH-brandId", "PATH-messagebaseId")
	},
	"getRcsTemplateImage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.TemplateImages.Get(ctx, bizgo.GetRCSTemplateImageParams{BrandID: "Q-brandId", FileID: "Q-fileId"})
	},
	"uploadRcsTemplateImage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.TemplateImages.Upload(ctx, &bizgo.RCSTemplateImageUploadRequest{BrandID: "x", File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}})
	},
	"listRcsTemplateFormLogos": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.RCS.TemplateImages.ListFormLogos(ctx, bizgo.ListRCSTemplateFormLogosParams{MessagebaseformID: "Q-messagebaseformId"})
	},
	"sendCounselPlain": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Counsel.Messages.SendPlain(ctx, &bizgo.CounselPlainMessageRequest{UserKey: "x", SenderKey: "x", MsgType: "TEXT", Message: "x"})
	},
	"sendCounselRich": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Counsel.Messages.SendRich(ctx, &bizgo.CounselRichMessageRequest{UserKey: "x", SenderKey: "x", MsgType: "x"})
	},
	"endCounselSession": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Counsel.Sessions.End(ctx, &bizgo.CounselEndRequest{UserKey: "x", SenderKey: "x"})
	},
	"endCounselSessionWithBot": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Counsel.Sessions.EndWithBot(ctx, &bizgo.CounselEndWithBotRequest{UserKey: "x", SenderKey: "x"})
	},
	"blockCounselUser": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Counsel.Users.Block(ctx, &bizgo.CounselUserBlockRequest{Cstalk: &bizgo.CounselUserTarget{SenderKey: "x", UserKey: "x"}})
	},
	"unblockCounselUser": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Counsel.Users.Unblock(ctx, &bizgo.CounselUserBlockRequest{Cstalk: &bizgo.CounselUserTarget{SenderKey: "x", UserKey: "x"}})
	},
	"getCounselSession": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Counsel.Sessions.Get(ctx, bizgo.GetCounselSessionParams{UserKey: "x"})
	},
	"getCounselCertStatus": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Counsel.Certs.Get(ctx, bizgo.GetCounselCertStatusParams{CertTxID: "Q-certTxId"})
	},
	"uploadCounselImage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Counsel.Files.UploadImage(ctx, &bizgo.CounselImageUploadRequest{File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}, SenderKey: "x"})
	},
	"uploadCounselFile": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Counsel.Files.Upload(ctx, &bizgo.CounselFileUploadRequest{File: &bizgo.UploadFile{Reader: strings.NewReader("sample"), Filename: "sample.jpg"}, SenderKey: "x"})
	},
	"activateCounsel": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Counsel.Channels.Activate(ctx, &bizgo.CounselSenderActivationRequest{Cstalk: &bizgo.CounselSenderActivation{SenderKey: "x"}})
	},
	"deactivateCounsel": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Counsel.Channels.Deactivate(ctx, &bizgo.CounselSenderActivationRequest{Cstalk: &bizgo.CounselSenderActivation{SenderKey: "x"}})
	},
	"activateCounselChat": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Counsel.Channels.ActivateChat(ctx, &bizgo.CounselSenderRequest{Cstalk: &bizgo.CounselSenderRef{SenderKey: "x"}})
	},
	"deactivateCounselChat": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Counsel.Channels.DeactivateChat(ctx, &bizgo.CounselSenderRequest{Cstalk: &bizgo.CounselSenderRef{SenderKey: "x"}})
	},
	"getCounselConsultTime": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Counsel.ConsultTime.Get(ctx, bizgo.GetCounselConsultTimeParams{SenderKey: "Q-senderKey"})
	},
	"saveCounselConsultTime": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Counsel.ConsultTime.Save(ctx, &bizgo.CounselConsultTimeSaveRequest{Cstalk: &bizgo.CounselConsultTimeSetting{SenderKey: "x", WeekTimeTable: []bizgo.CounselWeekTime{{Day: "mon", StartAt: "x", EndAt: "x"}}}})
	},
	"listCounselSystemMessages": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Counsel.SystemMessages.List(ctx, bizgo.ListCounselSystemMessagesParams{SenderKey: "Q-senderKey"})
	},
	"createCounselSystemMessage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return c.Counsel.SystemMessages.Create(ctx, &bizgo.CounselSystemMessageCreateRequest{Cstalk: &bizgo.CounselSystemMessageDraft{SenderKey: "x", Name: "x", Messages: []bizgo.CounselSystemMessageContent{{MessageType: "x", Content: "x", Buttons: []bizgo.CounselSystemMessageButton{{Ordering: 1, Type: "x", Name: "x"}}}}}})
	},
	"deleteCounselSystemMessage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Counsel.SystemMessages.Delete(ctx, "PATH-senderKey", "PATH-id")
	},
	"requestCounselSystemMessageApproval": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Counsel.SystemMessages.RequestApproval(ctx, &bizgo.CounselSenderRequest{Cstalk: &bizgo.CounselSenderRef{SenderKey: "x"}})
	},
	"cancelCounselSystemMessageApproval": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Counsel.SystemMessages.CancelApproval(ctx, &bizgo.CounselSenderRequest{Cstalk: &bizgo.CounselSenderRef{SenderKey: "x"}})
	},
	"deleteCounselMessage": func(ctx context.Context, c *bizgo.Client) (any, error) {
		return nil, c.Counsel.Messages.Delete(ctx, &bizgo.CounselMessageDeleteRequest{Cstalk: &bizgo.CounselMessageDeleteTarget{SenderKey: "x", UserKey: "x", MsgKey: "x"}})
	},
}

// generatedVoid lists the generated methods that return only an error.
var generatedVoid = map[string]bool{
	"deleteReservationRecipient":              true,
	"recoverKakaoSender":                      true,
	"addKakaoGroupSender":                     true,
	"removeKakaoGroupSender":                  true,
	"deleteAlimtalkTemplate":                  true,
	"requestAlimtalkTemplateInspection":       true,
	"requestAlimtalkTemplateInspection+files": true,
	"cancelAlimtalkTemplateInspection":        true,
	"checkBrandMessageSendPermission":         true,
	"applyBrandMessageSendPermission":         true,
	"deleteBrandMessageTemplate":              true,
	"deleteBrandMessageGroupTag":              true,
	"deleteBrandMessageFriendGroup":           true,
	"registerBrandMessageUnsubscribeContent":  true,
	"blockCounselUser":                        true,
	"unblockCounselUser":                      true,
	"activateCounsel":                         true,
	"deactivateCounsel":                       true,
	"activateCounselChat":                     true,
	"deactivateCounselChat":                   true,
	"saveCounselConsultTime":                  true,
	"deleteCounselSystemMessage":              true,
	"requestCounselSystemMessageApproval":     true,
	"cancelCounselSystemMessageApproval":      true,
	"deleteCounselMessage":                    true,
}

// generatedIterators walks the iterator of every generated paginated method.
var generatedIterators = map[string]func(context.Context, *bizgo.Client) (int, error){
	"listReservations": func(ctx context.Context, c *bizgo.Client) (int, error) {
		n := 0
		for _, err := range c.Reservations.IterList(ctx, bizgo.ListReservationsParams{ResvSendTime: bizgo.Date(2026, time.January, 2)}) {
			if err != nil {
				return n, err
			}
			n++
		}
		return n, nil
	},
	"listReservationRecipients": func(ctx context.Context, c *bizgo.Client) (int, error) {
		n := 0
		for _, err := range c.Reservations.Recipients.IterList(ctx, "PATH-resvKey", bizgo.ListReservationRecipientsParams{}) {
			if err != nil {
				return n, err
			}
			n++
		}
		return n, nil
	},
	"listKakaoSenderProfiles": func(ctx context.Context, c *bizgo.Client) (int, error) {
		n := 0
		for _, err := range c.Kakao.Senders.IterList(ctx, bizgo.ListKakaoSenderProfilesParams{}) {
			if err != nil {
				return n, err
			}
			n++
		}
		return n, nil
	},
	"listAlimtalkTemplates": func(ctx context.Context, c *bizgo.Client) (int, error) {
		n := 0
		for _, err := range c.Alimtalk.Templates.IterList(ctx, bizgo.ListAlimtalkTemplatesParams{SenderKey: "Q-senderKey"}) {
			if err != nil {
				return n, err
			}
			n++
		}
		return n, nil
	},
	"listModifiedAlimtalkTemplates": func(ctx context.Context, c *bizgo.Client) (int, error) {
		n := 0
		for _, err := range c.Alimtalk.Templates.IterListModified(ctx, bizgo.ListModifiedAlimtalkTemplatesParams{SenderKey: "Q-senderKey"}) {
			if err != nil {
				return n, err
			}
			n++
		}
		return n, nil
	},
	"listAlimtalkPublicTemplates": func(ctx context.Context, c *bizgo.Client) (int, error) {
		n := 0
		for _, err := range c.Alimtalk.PublicTemplates.IterList(ctx, bizgo.ListAlimtalkPublicTemplatesParams{}) {
			if err != nil {
				return n, err
			}
			n++
		}
		return n, nil
	},
	"listBrandMessageVideos": func(ctx context.Context, c *bizgo.Client) (int, error) {
		n := 0
		for _, err := range c.BrandMessage.Videos.IterList(ctx, bizgo.ListBrandMessageVideosParams{SenderKey: "Q-senderKey"}) {
			if err != nil {
				return n, err
			}
			n++
		}
		return n, nil
	},
	"listBrandMessageTemplates": func(ctx context.Context, c *bizgo.Client) (int, error) {
		n := 0
		for _, err := range c.BrandMessage.Templates.IterList(ctx, bizgo.ListBrandMessageTemplatesParams{SenderKey: "Q-senderKey"}) {
			if err != nil {
				return n, err
			}
			n++
		}
		return n, nil
	},
	"listBrandMessageTemplatesLastModified": func(ctx context.Context, c *bizgo.Client) (int, error) {
		n := 0
		for _, err := range c.BrandMessage.Templates.IterListLastModified(ctx, bizgo.ListBrandMessageTemplatesLastModifiedParams{SenderKey: "Q-senderKey"}) {
			if err != nil {
				return n, err
			}
			n++
		}
		return n, nil
	},
	"listBrandMessageFriendGroupPhoneNumberRequests": func(ctx context.Context, c *bizgo.Client) (int, error) {
		n := 0
		for _, err := range c.BrandMessage.FriendGroups.IterListPhoneNumberRequests(ctx, bizgo.ListBrandMessageFriendGroupPhoneNumberRequestsParams{SenderKey: "Q-senderKey", FriendGroupKey: "Q-friendGroupKey"}) {
			if err != nil {
				return n, err
			}
			n++
		}
		return n, nil
	},
	"listRcsChatbots": func(ctx context.Context, c *bizgo.Client) (int, error) {
		n := 0
		for _, err := range c.RCS.Chatbots.IterList(ctx, bizgo.ListRCSChatbotsParams{BrandID: "Q-brandId"}) {
			if err != nil {
				return n, err
			}
			n++
		}
		return n, nil
	},
	"listRcsTemplateForms": func(ctx context.Context, c *bizgo.Client) (int, error) {
		n := 0
		for _, err := range c.RCS.TemplateForms.IterList(ctx, bizgo.ListRCSTemplateFormsParams{}) {
			if err != nil {
				return n, err
			}
			n++
		}
		return n, nil
	},
}

// pageItemSamples is one JSON item of a page of every paginated operation (generated or hand-written).
var pageItemSamples = map[string]string{
	"getMessageHistory":                              "{}",
	"getMoHistory":                                   "{}",
	"listReservations":                               "{}",
	"listReservationRecipients":                      "{}",
	"listKakaoSenderProfiles":                        "{}",
	"listAlimtalkTemplates":                          "{}",
	"listModifiedAlimtalkTemplates":                  "{}",
	"listAlimtalkPublicTemplates":                    "{}",
	"listBrandMessageVideos":                         "{}",
	"listBrandMessageTemplates":                      "{}",
	"listBrandMessageTemplatesLastModified":          "{}",
	"listBrandMessageFriendGroupPhoneNumberRequests": "{}",
	"listRcsChatbots":                                "{}",
	"listRcsTemplateForms":                           "{}",
}

var _ = time.January
