// Code generated by tools/gen from spec/openapi.yaml. DO NOT EDIT.

package bizgo

import (
	"context"
	"net/http"
)

// webhookTable lists the webhooks of the spec (x-sdk-webhook) for tests.
var webhookTable = []webhookInfo{
	{name: "counselCertResult", id: "onCounselCertResultWebhook", signed: false, handwritten: false},
	{name: "counselExpiredSession", id: "onCounselExpiredSessionWebhook", signed: false, handwritten: false},
	{name: "counselMessage", id: "onCounselMessageWebhook", signed: false, handwritten: false},
	{name: "counselPersonalInfo", id: "onCounselPersonalInfoWebhook", signed: false, handwritten: false},
	{name: "counselReference", id: "onCounselReferenceWebhook", signed: false, handwritten: false},
	{name: "counselResult", id: "onCounselResultWebhook", signed: false, handwritten: false},
	{name: "counselSeenInfo", id: "onCounselSeenInfoWebhook", signed: false, handwritten: false},
	{name: "mo", id: "onMoWebhook", signed: true, handwritten: true},
	{name: "report", id: "onReportWebhook", signed: true, handwritten: true},
}

// ParseCounselCertResultWebhook parses a counselCertResult webhook body (상담톡 본인인증 결과 수신(Webhook)). It needs no receiver and no
// webhook secret: this webhook has no signature (Bizgo signs only report and MO webhooks). The body
// checks (1MB, JSON depth 64, field types) apply.
func ParseCounselCertResultWebhook(body []byte) (*CounselCertResultWebhookPayload, error) {
	return parseWebhook[CounselCertResultWebhookPayload](body)
}

// CounselCertResult parses a counselCertResult webhook body (상담톡 본인인증 결과 수신(Webhook)), like [ParseCounselCertResultWebhook].
//
// This webhook has no signature, so the headers are not checked: X-IB-Timestamp and
// X-IB-Signature are ignored if present.
func (r *WebhookReceiver) CounselCertResult(_ http.Header, body []byte) (*CounselCertResultWebhookPayload, error) {
	return ParseCounselCertResultWebhook(body)
}

// CounselCertResultHandler returns an http.Handler for counselCertResult webhooks: it reads at most 1MB, parses the body (400 on failure),
// calls fn (500 without the ack if fn fails, so Bizgo retries) and acknowledges. It answers {"code": "A000", "result": "Success"}.
func (r *WebhookReceiver) CounselCertResultHandler(fn func(context.Context, *CounselCertResultWebhookPayload) error) http.Handler {
	return webhookHandler(nil, ParseCounselCertResultWebhook, fn, func(*CounselCertResultWebhookPayload) any { return CounselWebhookAck{Code: "A000", Result: "Success"} })
}

// ParseCounselExpiredSessionWebhook parses a counselExpiredSession webhook body (상담톡 세션 종료 수신(Webhook)). It needs no receiver and no
// webhook secret: this webhook has no signature (Bizgo signs only report and MO webhooks). The body
// checks (1MB, JSON depth 64, field types) apply.
func ParseCounselExpiredSessionWebhook(body []byte) (*CounselExpiredSessionWebhookPayload, error) {
	return parseWebhook[CounselExpiredSessionWebhookPayload](body)
}

// CounselExpiredSession parses a counselExpiredSession webhook body (상담톡 세션 종료 수신(Webhook)), like [ParseCounselExpiredSessionWebhook].
//
// This webhook has no signature, so the headers are not checked: X-IB-Timestamp and
// X-IB-Signature are ignored if present.
func (r *WebhookReceiver) CounselExpiredSession(_ http.Header, body []byte) (*CounselExpiredSessionWebhookPayload, error) {
	return ParseCounselExpiredSessionWebhook(body)
}

// CounselExpiredSessionHandler returns an http.Handler for counselExpiredSession webhooks: it reads at most 1MB, parses the body (400 on failure),
// calls fn (500 without the ack if fn fails, so Bizgo retries) and acknowledges. It answers {"code": "A000", "result": "Success"}.
func (r *WebhookReceiver) CounselExpiredSessionHandler(fn func(context.Context, *CounselExpiredSessionWebhookPayload) error) http.Handler {
	return webhookHandler(nil, ParseCounselExpiredSessionWebhook, fn, func(*CounselExpiredSessionWebhookPayload) any {
		return CounselWebhookAck{Code: "A000", Result: "Success"}
	})
}

// ParseCounselMessageWebhook parses a counselMessage webhook body (상담톡 사용자 메시지 수신(Webhook)). It needs no receiver and no
// webhook secret: this webhook has no signature (Bizgo signs only report and MO webhooks). The body
// checks (1MB, JSON depth 64, field types) apply.
func ParseCounselMessageWebhook(body []byte) (*CounselMessageWebhookPayload, error) {
	return parseWebhook[CounselMessageWebhookPayload](body)
}

// CounselMessage parses a counselMessage webhook body (상담톡 사용자 메시지 수신(Webhook)), like [ParseCounselMessageWebhook].
//
// This webhook has no signature, so the headers are not checked: X-IB-Timestamp and
// X-IB-Signature are ignored if present.
func (r *WebhookReceiver) CounselMessage(_ http.Header, body []byte) (*CounselMessageWebhookPayload, error) {
	return ParseCounselMessageWebhook(body)
}

// CounselMessageHandler returns an http.Handler for counselMessage webhooks: it reads at most 1MB, parses the body (400 on failure),
// calls fn (500 without the ack if fn fails, so Bizgo retries) and acknowledges. It answers {"code": "A000", "result": "Success"}.
func (r *WebhookReceiver) CounselMessageHandler(fn func(context.Context, *CounselMessageWebhookPayload) error) http.Handler {
	return webhookHandler(nil, ParseCounselMessageWebhook, fn, func(*CounselMessageWebhookPayload) any { return CounselWebhookAck{Code: "A000", Result: "Success"} })
}

// ParseCounselPersonalInfoWebhook parses a counselPersonalInfo webhook body (상담톡 개인정보 수신(Webhook)). It needs no receiver and no
// webhook secret: this webhook has no signature (Bizgo signs only report and MO webhooks). The body
// checks (1MB, JSON depth 64, field types) apply.
func ParseCounselPersonalInfoWebhook(body []byte) (*CounselPersonalInfoWebhookPayload, error) {
	return parseWebhook[CounselPersonalInfoWebhookPayload](body)
}

// CounselPersonalInfo parses a counselPersonalInfo webhook body (상담톡 개인정보 수신(Webhook)), like [ParseCounselPersonalInfoWebhook].
//
// This webhook has no signature, so the headers are not checked: X-IB-Timestamp and
// X-IB-Signature are ignored if present.
func (r *WebhookReceiver) CounselPersonalInfo(_ http.Header, body []byte) (*CounselPersonalInfoWebhookPayload, error) {
	return ParseCounselPersonalInfoWebhook(body)
}

// CounselPersonalInfoHandler returns an http.Handler for counselPersonalInfo webhooks: it reads at most 1MB, parses the body (400 on failure),
// calls fn (500 without the ack if fn fails, so Bizgo retries) and acknowledges. It answers {"code": "A000", "result": "Success"}.
func (r *WebhookReceiver) CounselPersonalInfoHandler(fn func(context.Context, *CounselPersonalInfoWebhookPayload) error) http.Handler {
	return webhookHandler(nil, ParseCounselPersonalInfoWebhook, fn, func(*CounselPersonalInfoWebhookPayload) any {
		return CounselWebhookAck{Code: "A000", Result: "Success"}
	})
}

// ParseCounselReferenceWebhook parses a counselReference webhook body (상담톡 사용자 메타 정보 수신(Webhook)). It needs no receiver and no
// webhook secret: this webhook has no signature (Bizgo signs only report and MO webhooks). The body
// checks (1MB, JSON depth 64, field types) apply.
func ParseCounselReferenceWebhook(body []byte) (*CounselReferenceWebhookPayload, error) {
	return parseWebhook[CounselReferenceWebhookPayload](body)
}

// CounselReference parses a counselReference webhook body (상담톡 사용자 메타 정보 수신(Webhook)), like [ParseCounselReferenceWebhook].
//
// This webhook has no signature, so the headers are not checked: X-IB-Timestamp and
// X-IB-Signature are ignored if present.
func (r *WebhookReceiver) CounselReference(_ http.Header, body []byte) (*CounselReferenceWebhookPayload, error) {
	return ParseCounselReferenceWebhook(body)
}

// CounselReferenceHandler returns an http.Handler for counselReference webhooks: it reads at most 1MB, parses the body (400 on failure),
// calls fn (500 without the ack if fn fails, so Bizgo retries) and acknowledges. It answers {"code": "A000", "result": "Success"}.
func (r *WebhookReceiver) CounselReferenceHandler(fn func(context.Context, *CounselReferenceWebhookPayload) error) http.Handler {
	return webhookHandler(nil, ParseCounselReferenceWebhook, fn, func(*CounselReferenceWebhookPayload) any { return CounselWebhookAck{Code: "A000", Result: "Success"} })
}

// ParseCounselResultWebhook parses a counselResult webhook body (상담톡 발송 결과 수신(Webhook)). It needs no receiver and no
// webhook secret: this webhook has no signature (Bizgo signs only report and MO webhooks). The body
// checks (1MB, JSON depth 64, field types) apply.
func ParseCounselResultWebhook(body []byte) (*CounselResultWebhookPayload, error) {
	return parseWebhook[CounselResultWebhookPayload](body)
}

// CounselResult parses a counselResult webhook body (상담톡 발송 결과 수신(Webhook)), like [ParseCounselResultWebhook].
//
// This webhook has no signature, so the headers are not checked: X-IB-Timestamp and
// X-IB-Signature are ignored if present.
func (r *WebhookReceiver) CounselResult(_ http.Header, body []byte) (*CounselResultWebhookPayload, error) {
	return ParseCounselResultWebhook(body)
}

// CounselResultHandler returns an http.Handler for counselResult webhooks: it reads at most 1MB, parses the body (400 on failure),
// calls fn (500 without the ack if fn fails, so Bizgo retries) and acknowledges. It answers {"code": "A000", "result": "Success"}.
func (r *WebhookReceiver) CounselResultHandler(fn func(context.Context, *CounselResultWebhookPayload) error) http.Handler {
	return webhookHandler(nil, ParseCounselResultWebhook, fn, func(*CounselResultWebhookPayload) any { return CounselWebhookAck{Code: "A000", Result: "Success"} })
}

// ParseCounselSeenInfoWebhook parses a counselSeenInfo webhook body (상담톡 읽음 정보 수신(Webhook)). It needs no receiver and no
// webhook secret: this webhook has no signature (Bizgo signs only report and MO webhooks). The body
// checks (1MB, JSON depth 64, field types) apply.
func ParseCounselSeenInfoWebhook(body []byte) (*CounselSeenInfoWebhookPayload, error) {
	return parseWebhook[CounselSeenInfoWebhookPayload](body)
}

// CounselSeenInfo parses a counselSeenInfo webhook body (상담톡 읽음 정보 수신(Webhook)), like [ParseCounselSeenInfoWebhook].
//
// This webhook has no signature, so the headers are not checked: X-IB-Timestamp and
// X-IB-Signature are ignored if present.
func (r *WebhookReceiver) CounselSeenInfo(_ http.Header, body []byte) (*CounselSeenInfoWebhookPayload, error) {
	return ParseCounselSeenInfoWebhook(body)
}

// CounselSeenInfoHandler returns an http.Handler for counselSeenInfo webhooks: it reads at most 1MB, parses the body (400 on failure),
// calls fn (500 without the ack if fn fails, so Bizgo retries) and acknowledges. It answers {"code": "A000", "result": "Success"}.
func (r *WebhookReceiver) CounselSeenInfoHandler(fn func(context.Context, *CounselSeenInfoWebhookPayload) error) http.Handler {
	return webhookHandler(nil, ParseCounselSeenInfoWebhook, fn, func(*CounselSeenInfoWebhookPayload) any { return CounselWebhookAck{Code: "A000", Result: "Success"} })
}
